### ISSUE TITLE
Warning message in console when running `sanity start`

### ISSUE THREAD

**Issue by coreyward** [robinpyon/sanity-plugin-media#21] opened 2021-01-25 23:11 UTC
I'm seeing this error in the terminal each time a file is saved/reloaded:

> Warning in ./node_modules/sanity-plugin-media/node_modules/framer-motion/dist/framer-motion.es.js
743:18-24 "export 'filter' was not found in 'style-value-types'

Using v1.0.1:

```
sanity-plugin-media@^1.0.1:
  version "1.0.1"
  resolved "https://registry.yarnpkg.com/sanity-plugin-media/-/sanity-plugin-media-1.0.1.tgz#2c25cf1d82b15a7f6ae09266fc9958c9b65d600f"
  integrity sha512-bs0U8MtoNPUQndv1iCszlWtVhxny6D1bHayB4WEGNJc+l7bnZC/1RWzEJ5yeULRK0bgNvBMjSXrweuEvKy5tUA==
  dependencies:
    "@hookform/resolvers" "2.0.0-beta.3"
    "@sanity/components" "2.1.0"
    "@sanity/icons" "1.0.1"
    "@sanity/ui" "0.32.2"
    "@tanem/react-nprogress" "3.0.52"
    date-fns "2.16.1"
    filesize "6.1.0"
    groq "2.0.9"
    immer "8.0.0"
    is-hotkey "0.2.0"
    pluralize "8.0.0"
    react-file-icon "1.0.0"
    react-hook-form "6.14.0"
    react-redux "7.2.2"
    react-select "3.1.1"
    react-virtualized-auto-sizer "1.0.3"
    react-window "1.8.6"
    react-window-infinite-loader "1.0.5"
    redux "4.0.5"
    redux-devtools-extension "2.13.8"
    redux-observable "1.2.0"
    rxjs "6.6.3"
    styled-components "5.2.1"
    theme-ui "0.3.5"
    typesafe-actions "5.1.0"
    yup "0.32.8"
```

**Comment by robinpyon** [comment] 2021-01-26 12:30
Thanks @coreyward

Can you please run `sanity versions` and paste your result here?

**Comment by coreyward** [comment] 2021-01-26 14:34
Sure thing.

```
@sanity/cli             2.1.4 (latest: 2.2.2)
@sanity/base            2.1.4 (latest: 2.2.2)
@sanity/color-input     2.1.4 (up to date)
@sanity/components      2.1.4 (up to date)
@sanity/core            2.1.4 (latest: 2.2.2)
@sanity/default-layout  2.1.4 (latest: 2.2.2)
@sanity/default-login   2.1.4 (up to date)
@sanity/desk-tool       2.1.4 (latest: 2.2.2)
@sanity/vision          2.1.4 (up to date)
```

**Comment by robinpyon** [comment] 2021-01-27 00:45
Thanks. Please try `1.0.2-beta.0` and let me know if that solves things for you.

I'm unable to replicate here – but I believe the issue is linked to multiple loaded copies of `@sanity/ui`.

**Comment by coreyward** [comment] 2021-01-27 23:28
Okay, so I tried updating, but it breaks the Studio entirely with this error showing in the browser: 

<img width="513" alt="Screen Shot 2021-01-27 at 5 20 08 PM" src="https://user-images.githubusercontent.com/81224/106067286-ffb6ee80-60c3-11eb-8091-7c503e1cb9f9.png">

Looks like it's coming from here:

<img width="526" alt="Screen Shot 2021-01-27 at 5 20 39 PM" src="https://user-images.githubusercontent.com/81224/106067301-080f2980-60c4-11eb-83e1-6b0876c02852.png">

Here's what `yarn why @sanity/ui` looks like with 1.0.2-beta.0:

```
yarn why v1.22.4
[1/4] 🤔  Why do we have the module "@sanity/ui"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@sanity/ui@0.28.0"
info Reasons this module exists
   - "@sanity#base" depends on it
   - Hoisted from "@sanity#base#@sanity#ui"
   - Hoisted from "@sanity#desk-tool#@sanity#form-builder#@sanity#ui"
info Disk size without dependencies: "6.72MB"
info Disk size with unique dependencies: "18.75MB"
info Disk size with transitive dependencies: "25.41MB"
info Number of shared dependencies: 20
✨  Done in 0.75s.
```

Versus on 1.0.1:

```
yarn why v1.22.4
[1/4] 🤔  Why do we have the module "@sanity/ui"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@sanity/ui@0.28.0"
info Has been hoisted to "@sanity/ui"
info Reasons this module exists
   - Hoisted from "@sanity#base#@sanity#ui"
   - Hoisted from "@sanity#desk-tool#@sanity#form-builder#@sanity#ui"
info Disk size without dependencies: "6.63MB"
info Disk size with unique dependencies: "18.64MB"
info Disk size with transitive dependencies: "25.21MB"
info Number of shared dependencies: 24
=> Found "sanity-plugin-media#@sanity/ui@0.32.2"
info This module exists because "sanity-plugin-media" depends on it.
info Disk size without dependencies: "12.73MB"
info Disk size with unique dependencies: "24.74MB"
info Disk size with transitive dependencies: "31.32MB"
info Number of shared dependencies: 24
✨  Done in 1.57s.
```

Oddly, when I revert the change to `package.json` and re-run `yarn install`, I'm left with some changes to `yarn.lock` and the error seems to go away:

```diff
diff --git a/yarn.lock b/yarn.lock
index cdaeb3e..098b153 100644
--- a/yarn.lock
+++ b/yarn.lock
@@ -4763,6 +4763,11 @@ framer-motion@^3.1.3:
   optionalDependencies:
     "@emotion/is-prop-valid" "^0.8.2"
 
+framesync@5.0.0, framesync@^5.0.0:
+  version "5.0.0"
+  resolved "https://registry.yarnpkg.com/framesync/-/framesync-5.0.0.tgz#7de8caedf53ac441118e79680f1beb7391c328b6"
+  integrity sha512-wd8t+JsQGisluSv1twiEeDv0aNGpavGb9q7xgIk9fGbcIWkNXF/KVtrjnOrCwBWJuiXxlJfNkcvGudsI32FxYA==
+
 framesync@^4.1.0:
   version "4.1.0"
   resolved "https://registry.npmjs.org/framesync/-/framesync-4.1.0.tgz#69a8db3ca432dc70d6a76ba882684a1497ef068a"
@@ -7104,6 +7109,16 @@ popmotion@9.0.0-rc.20:
     style-value-types "^3.1.9"
     tslib "^1.10.0"
 
+popmotion@^9.1.0:
+  version "9.1.0"
+  resolved "https://registry.yarnpkg.com/popmotion/-/popmotion-9.1.0.tgz#4360d06bd18ce8baa8f9284ecec7d55344af6325"
+  integrity sha512-+J7pzzBy5kk2qsP8ilowKs/CH+HoZa3kOGEBNCleCvsPXEF3nKHdfAR3SboMyPvdpIrofaT7ZIy/xWgz446Azw==
+  dependencies:
+    framesync "5.0.0"
+    hey-listen "^1.0.8"
+    style-value-types "^4.0.1"
+    tslib "^1.10.0"
+
 popper-max-size-modifier@^0.2.0:
   version "0.2.0"
   resolved "https://registry.npmjs.org/popper-max-size-modifier/-/popper-max-size-modifier-0.2.0.tgz#1574744401296a488b4974909d130a85db94256f"
@@ -8366,9 +8381,10 @@ redux@4.0.5:
     loose-envify "^1.4.0"
     symbol-observable "^1.2.0"
 
-refractor@^3.1.0:
-  version "3.3.0"
-  resolved "https://registry.npmjs.org/refractor/-/refractor-3.3.0.tgz#42a7d58f14a1d1bcda52a8c66123601a71e5d47d"
+refractor@^3.3.0:
+  version "3.3.1"
+  resolved "https://registry.yarnpkg.com/refractor/-/refractor-3.3.1.tgz#ebbc04b427ea81dc25ad333f7f67a0b5f4f0be3a"
+  integrity sha512-vaN6R56kLMuBszHSWlwTpcZ8KTMG6aUCok4GrxYDT20UIOXxOc5o6oDc8tNTzSlH3m2sI+Eu9Jo2kVdDcUTWYw==
   dependencies:
     hastscript "^6.0.0"
     parse-entities "^2.0.0"
@@ -9270,6 +9286,14 @@ style-value-types@^3.1.9:
     hey-listen "^1.0.8"
     tslib "^1.10.0"
 
+style-value-types@^4.0.1:
+  version "4.0.1"
+  resolved "https://registry.yarnpkg.com/style-value-types/-/style-value-types-4.0.1.tgz#23f05dd03e8a850654defc22cf03ebac572aaa00"
+  integrity sha512-aOV/HHyynIyTmU27qfs0oAHhFde6BFIvV4+nMerE2MAPZMwYOeQk1/F3S6djxF2u4HdbiieCPs3ZzWsbNUoc9A==
+  dependencies:
+    hey-listen "^1.0.8"
+    tslib "^1.10.0"
+
 styled-components@5.2.1, styled-components@^5.0.0, styled-components@^5.2.1:
   version "5.2.1"
   resolved "https://registry.npmjs.org/styled-components/-/styled-components-5.2.1.tgz#6ed7fad2dc233825f64c719ffbdedd84ad79101a"
```

Notably, though, with 1.0.1 installed, even with this reverted-but-changed-lockfile, I experience boot times around 17–18 seconds. With 1.0.2-beta.0 it was 2 seconds. So I think there's still something going on.

**Comment by robinpyon** [comment] 2021-01-28 00:18
@coreyward Thanks so much for the above info.

The only change in `1.0.2-beta.0` is that `@sanity/ui` is now listed as a peer dependency.

It _should_ have worked with the version of `@sanity/base` you've listed  and according to their docs, Sanity ships with a version of it. I tried replicating on the exact same versions and had no issue – so, I'm quite stumped! 

But if you managed to get it resolved by reinstalling your deps, I'll gladly accept that and keep things the way they were!

>  With 1.0.2-beta.0 it was 2 seconds.

Can you confirm that boot time of 2 seconds or was that a typo? Did you mean 20?

**Comment by coreyward** [comment] 2021-01-28 17:02
Ahhh okay so I think what's causing this is compatibility issue with the shared dependency is the (incorrect?) dependency from @sanity/base on @sanity/color@^1.0.0 which does not export a `hues` named export. 

https://github.com/sanity-io/sanity/blob/2e80f0af5776c43328b4c4fd17139cbc27e34382/packages/%40sanity/base/package.json#L36

And yep, I don't know if maybe the 2s (2013ms) boot time was leveraging cache or what, but that's what was reported in the terminal when I updated to v1.0.2-beta.0.

**Comment by robinpyon** [comment] 2021-02-01 22:34
Looks like you're right – @sanity/base is pointing to  @sanity/color `^1.0.0` whilst @sanity/ui asks for `^2.0.11` (which @sanity/base includes as a dependency)

Though I'm not sure why this would have caused in an issue – my understanding is that yarn / npm adds the duplicate @sanity/color `^1.0.0` package in @sanity/base as a private, non-hoisted version (which should work when both versions are installed)

In any case, I'll close this out for now and will continue to include @sanity/ui as a dependency. Please let me know if it rears its head again!

**Closed by robinpyon** 2021-02-01 22:34 UTC
